config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "users#index"

  get '/public_recipes', to: 'recipes#public'
  resources :foods, only: [:index, :new, :create, :destroy]
  
  resources :recipes do
    resources :meal_ingredients, only: [:new, :create, :destroy, :edit, :update], as: :modify_meal_ingredient
    resources :recipe_foods, only: [:create, :destroy, :update], controller: 'meal_ingredients'
    member do
      match 'general_shopping_list', to: 'recipes#general_shopping_list', via: [:get, :post]
    end
  end  
end

app/controllers/meal_ingredients_controller.rb
class MealIngredientsController < ApplicationController
  def show
    recipe_food = RecipeFood.find(params[:id])
    redirect_to recipe_path(recipe_food.recipe)
  end

  def new
    @user = current_user
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @ingredients = @user.foods&.map { |food| "#{food.name} in #{food.measurement_unit}" } || []
    @foods = Food.all
  end

  def create
    recipe = Recipe.find(params[:recipe_id])
    food = Food.find(params[:recipe_food][:food])
    quantity = params[:recipe_food][:quantity]

    recipe_food = RecipeFood.new(food:, recipe:, quantity:)
    recipe_food.calculate_value

    if recipe_food.save
      flash[:success] = 'Added successfully'
      redirect_to recipe_path(recipe), format: :turbo_stream
    else
      flash[:error] = 'Failed to add ingredient'
      render 'new'
    end
  end

  def update
    recipe_food = RecipeFood.find(params[:id])
    recipe_food.update(quantity: params[:recipe_food][:quantity])

    flash[:success] = 'Updated successfully'
    redirect_to recipe_path(recipe_food.recipe)
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    recipe_food.destroy

    flash[:success] = 'Ingredient removed successfully'
    redirect_to recipe_path(recipe_food.recipe)
  end
end

app/helpers/meal_ingredients_helper.rb
module MealIngredientsHelper
end

app/views/meal_ingredients/new.html.erb
<div class="add-ingredient-form-container">
  <h4 class="form-title">Add Ingredient(s)</h4>
  <%= form_with model: [@recipe, @recipe_food], url: recipe_modify_meal_ingredient_index_path(@recipe), method: :post, local: true do |form| %>
    <div class="form-input noBorder">    
      <%= form.collection_select :food, @foods, :id, :name, { prompt: 'Pick ingredient...' }, class: 'ingredient-dropdown', style: 'height:40px;' %>

    </div>
    <div class="form-input noBorder">
      <%= form.text_field :quantity, placeholder: 'Enter quantity', required: true, class: 'quantity-input' %>
    </div>
    <div>
      <%= form.submit "Create Ingredient", class: "ingredient-buttons" %>
    </div>
    <div>
      <% if current_user == @recipe.user %>
        <%= link_to "Add Food", new_food_path, class: "ingredient-buttons", method: :get %>
        <% end %>
      <% end %>
    </div>
</div>