config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "users#index"

  get '/public_recipes', to: 'recipes#public'
  resources :foods, only: [:index, :new, :create, :destroy]
  
  resources :recipes do
    resources :meal_ingredients, only: [:new, :create, :destroy, :edit, :update], as: :modify_meal_ingredient
    resources :recipe_foods, only: [:create, :destroy, :update], controller: 'meal_ingredients'
    member do
      match 'general_shopping_list', to: 'recipes#general_shopping_list', via: [:get, :post]
    end
  end  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Successfully created.'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.user == current_user
      @recipe.destroy
      redirect_to recipes_path, notice: 'Successfully deleted.'
    else
      redirect_to recipes_path, alert: 'Cannot delete'
    end
  end

  def public
    @recipes = Recipe.where(public: true).order(created_at: :desc)
    render 'public'
  end

  def general_shopping_list
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find_by(id: params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    @needed_items = []
    @recipe_foods.each do |recipe_food|
      existed_food = @user.foods.find_by(name: recipe_food.food.name)
      if existed_food.nil?
        @needed_items << [recipe_food.food.name, recipe_food.quantity, recipe_food.food.price,
                          recipe_food.food.measurement_unit]
      else
        difference_quantity = recipe_food.quantity - existed_food.quantity
        if difference_quantity.positive?
          @needed_items << [recipe_food.food.name, difference_quantity, existed_food.price,
                            existed_food.measurement_unit]
        end
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Successfully updated.'
    else
      render :show
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/general_shopping_list.html.erb
<div class="shopping-list-container">
  <h3 class="shopping-list-title">Shopping list</h3>
  <div class="shopping-list-amount">
    <p>Amount of food items to buy: <%= @needed_items.length %></p>
    <p>Total value of food needed: <%= number_to_currency(@needed_items.sum { |item| item[1] * item[2] }, unit: "$") %></p>
  </div>

  <table class="shopping-list-table">
    <thead>
      <tr>
        <th class="shopping-list-header">Food</th>
        <th class="shopping-list-header">Quantity</th>
        <th class="shopping-list-header">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @needed_items.each do |needed_item| %>
        <tr>
          <td class="shopping-list-data"><%= needed_item[0] %></td>
          <td class="shopping-list-data"><%= needed_item[1] %> <%= needed_item[3] %></td>
          <td class="shopping-list-data"><%= number_to_currency(needed_item[1] * needed_item[2], unit: "$") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/index.html.erb
<h3 class="food-page-title">All Recipes</h3>
<div class="add-food-container">
  <%= link_to 'Create New Recipe', new_recipe_path, class: 'add-food-button' %></div>
</div>
<div>
  <% @recipes.each do |recipe| %>
    <div class="recipe-container">
      <div class="single-recipe">
        <h3 class="recipe-header">
          <%= link_to recipe.name, recipe %>
        </h3>
        <% if recipe.user == current_user %>
          <%= link_to 'Remove', recipe_path(recipe), data: { turbo_method: :delete, confirm: 'Please confirm deletion?' }, class: "recipe-delete" %>
        <% end %>
      </div>

      <div class="recipe-desc">
        <%= recipe.description %>
      </div>      
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>Create New Recipe</h1>

<div class="recipe-form">
  <%= form_with(model: @recipe, url: recipes_path) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :preparation_time %>
    <%= form.number_field :preparation_time %>

    <%= form.label :cooking_time %>
    <%= form.number_field :cooking_time %>

    <%= form.label :description %>
    <%= form.text_area :description %>

    <%= form.label :public %>
    <%= form.check_box :public %>

    <%= form.submit %>
  <% end %>
</div>

app/views/recipes/public.html.erb
<div class="public-recipes">
  <h3 class="Public-recipe-h3">Public Recipes</h3>
  <% @recipes.each do |recipe| %>
    <div class='recipe-box'>
      <div class='recipe-details'>
        <%= link_to "#{recipe.name}", recipe_path(recipe.id), class: 'recipe-name' %>
        <p class='user-name'>By: <%= recipe.user.name %></p>
      </div>
      <div class='recipe-totals'>
        <p>Total food items: <%= recipe.foods.count %></p>
        <p>Total price: $<%= recipe.foods.sum(:price) %></p>
      </div>
      <div>
        <% if recipe.user == current_user %>
          <%= link_to 'Remove', recipe_path(recipe), data: { turbo_method: :delete, confirm: 'Please confirm deletion?' }, class: "recipe-remove" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div id="recipe-display-container">
  <h1 id="recipe-title"><%= @recipe.name %></h1>
  <div id="recipe-display-box">
    <div class="recipe-info">
      <p>Preparation Time: <%= @recipe.preparation_time %> minutes</p>
      <p>Cooking Time: <%= @recipe.cooking_time %> minutes</p>
      <p>Description: <%= @recipe.description %></p>
    </div>
    <div>
      <% if current_user == @recipe.user || @recipe.public %>
        <%= form_for @recipe, url: recipe_path(@recipe), method: :patch, remote: true, html: { id: 'recipe-form' } do |f| %>
          <%= f.label :public, 'Public' %>
          <label class="switch">
            <%= f.check_box :public, id: 'public-checkbox' %>
            <span class="slider round"></span>
          </label>
          <%= f.submit 'Save', id: 'public-status-submit' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="action-buttons">
    <%= link_to "Generate Shopping List", general_shopping_list_recipe_path(@recipe), method: :post, class: "custom-button" %>
    <%= link_to "Add Ingredients", new_recipe_modify_meal_ingredient_path(@recipe), method: :get, class: "custom-button" %>
  </div>

  <section class="food-section">
    <table class="custom-table">
      <thead>
        <tr>
          <th class="table-header">Food</th>
          <th class="table-header">Quantity</th>
          <th class="table-header">Value</th>
          <th class="table-header">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if @recipe_foods.present? %>
          <% @recipe_foods.each do |recipe_food| %>
            <tr>
              <td class="table-data"><%= recipe_food.food.name %></td>
              <td class="table-data">
                <%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %>
              </td>
              <td class="table-data">
                <%= number_to_currency(recipe_food.value, unit: "$") %>
              </td>
              <td class="table-data">

                <div class="modify-form" style="display: none;" id="modify-form-<%= @recipe.id %>-<%= recipe_food.id %>">
                  <%= form_for recipe_food, url: recipe_recipe_food_path(@recipe, recipe_food), method: :patch, remote: true, html: { id: "modify-form-#{recipe_food.id}" } do |f| %>
                    <%= f.label :quantity %>
                    <%= f.text_field :quantity, value: recipe_food.quantity, name: 'recipe_food[quantity]' %>
                    <%= f.submit 'Update', class: 'modify-submit' %>
                  <% end %>
                </div>
                <div class="button-container">
                  <button class="action-button" data-recipe-id="<%= @recipe.id %>" data-food-id="<%= recipe_food.id %>">Modify</button>
                  <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'remove-button' %>
                </div>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="4">No Ingredients Available Now, Add Some!</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<%= javascript_include_tag "recipes" %>