config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "users#index"

  get '/public_recipes', to: 'recipes#public'
  resources :foods, only: [:index, :new, :create, :destroy]
  
  resources :recipes do
    resources :meal_ingredients, only: [:new, :create, :destroy, :edit, :update], as: :modify_meal_ingredient
    resources :recipe_foods, only: [:create, :destroy, :update], controller: 'meal_ingredients'
    member do
      match 'general_shopping_list', to: 'recipes#general_shopping_list', via: [:get, :post]
    end
  end  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: 'users_id'
  belongs_to :recipe, optional: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      flash[:success] = 'Food added successfully.'
      redirect_to foods_path
    else
      flash[:error] = 'Failed to add food.'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      flash[:notice] = 'Food deleted successfully.'
    else
      flash[:alert] = 'Failed to delete food.'
    end

    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<h3 class="food-page-title">Foods Page</h3>
<div class="add-food-container">
  <%= link_to "Add Food", new_food_path, method: :post, class: "add-food-button" %>
</div>
</div>
<table class="food-table">
  <thead>
    <tr>
      <th class="food-input-title" >Quantity</th>
      <th class="food-input-title" >Food</th>
      <th class="food-input-title" >Measurement unit</th>
      <th class="food-input-title">Unit price</th>
      <th class="food-input-title">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class="food-input"><%= food.quantity %></td>
        <td class="food-input"><%= food.name %></td>
        <td class="food-input"><%= food.measurement_unit %></td>
        <td class="food-input"><%= food.price %></td>
        <td class="food-input">
          <% if food.user == current_user %>
            <%= link_to 'Delete', food_path(food), data: { turbo_method: :delete, confirm: 'Please confirm deletion?' }, class: "delete" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<div class="food-form-container ff">
  <h3 class="Add-food-title">Add Food</h3>

  <%= form_with model: @food, url: foods_path do |form| %>
    <div class="food-input-container border">
      <%= form.text_field :name, placeholder: "Name", required: true %>
    </div>
    <div class="food-input-container border">
      <%= form.select :measurement_unit, options_for_select(['kg', 'pounds','units', 'grams']), { prompt: 'Unit measurement' }, class: 'form-select', style: 'height:37px; width:500px' %>
    </div>
    <div class="food-input-container border">
      <%= form.number_field :price, placeholder: "Price", required: true %>
    </div>
    <div class="food-input-container border">
      <%= form.number_field :quantity, placeholder: "Quantity", required: true %>
    </div>
    <%= form.submit "Add Food", class: "Create-food-button" %>
  <% end %>
</div>