config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  root to: "users#index"

  get '/public_recipes', to: 'recipes#public'
  resources :foods, only: [:index, :new, :create, :destroy]
  
  resources :recipes do
    resources :meal_ingredients, only: [:new, :create, :destroy, :edit, :update], as: :modify_meal_ingredient
    resources :recipe_foods, only: [:create, :destroy, :update], controller: 'meal_ingredients'
    member do
      match 'general_shopping_list', to: 'recipes#general_shopping_list', via: [:get, :post]
    end
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="nav">
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li>
            <%= link_to 'Recipes', recipes_path %>
            <ul>
              <li><%= link_to 'Create Recipe', new_recipe_path %></li>
            </ul>
          </li>
          <li>
            <%= link_to 'Foods', foods_path %>
            <ul>
              <li><%= link_to 'Create Food', new_food_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Public Recipes', public_recipes_path %></li>
          <!-- Add more navigation links as needed -->
        </ul>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>